sudo: false

language: scala

jdk:
  - oraclejdk8

env:
  - "IDEA_VERSION=2016.1.3;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/25793/php-145.970.40.zip"
  - "IDEA_VERSION=2016.2.5;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/27859/php-162.1628.23.zip"
  - "IDEA_VERSION=163.7342.3;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/30023/php-163.7342.9.zip"

script:
   - sbt test
   - sbt "; pluginPack ; pluginCompress ; pluginProguard"

matrix:
  allow_failures:
    # allow failure for EAP
    - env: "IDEA_VERSION=163.7342.3;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/30023/php-163.7342.9.zip"
